version: "3"

services:
  fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-api
    ports:
      - 8080:8000

# networks:
#   default:
#     name: rtf-network
#     external: true