version: "3"

services:
  fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-api
    ports:
      - 8888:8000
    networks:
      - rtf-network

networks:
  rtf-network:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16