version: "3"

services:
  fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-api
    ports:
      - 8888:8000
    networks:
      rtf-network:
        ipv4_address: 172.19.0.10

networks:
  rtf-network:
    name: rtf-network
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1