version: "3"

services:
  fast-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-api
    ports:
      - 8888:8000
    networks:
      default:
        ipv4_address: 172.23.0.15

networks:
  default:
    name: rtf-network
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
