version: "3"

services:
  ytn-news:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ytn-news
    environment:
      VIDEO_ID: "FJfwehhzIhw"
      KAFKA_TOPIC: "ytn-news"
  
  kbs-drama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kbs-drama
    environment:
      VIDEO_ID: "0GN8t2u3flc"
      KAFKA_TOPIC: "yonhap-news"

networks:
  default:
    name: rtf-network
    external: true
