version: "3"

services:
  ytn-news:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ytn-news
    environment:
      VIDEO_ID: "FJfwehhzIhw"
      KAFKA_TOPIC: "ytn-news"
  
  kbs-drama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kbs-drama
    environment:
      VIDEO_ID: "d7BbTmUZO-Y"
      KAFKA_TOPIC: "kbs-drama"

networks:
  default:
    name: rtf-network
    external: true
