version: "3"

services:
  data-preprocessor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-preprocessor

networks:
  default:
    name: rtf-network
    external: true